id: P010669
initial_creation_type: ocr
source_metadata:
  id: bdr:W21601
  title: འཁྲུངས་གླིང་།
  author: ''
  volumes:
    d2a02e5c6b784ece8b4663b74d605cc1:
      image_group_id: I1KG16898
      title: ''
      volume_number: 1
      total_pages: 498
